# Generated by Django 4.1.2 on 2022-10-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
