# Generated by Django 4.1.2 on 2022-10-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
