# Generated by Django 4.1.2 on 2022-10-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masseur', '0001_initial'),
        ('reservation', '0006_reservation_guest_email_reservation_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='masseur_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masseur.masseur'),
        ),
    ]
