# Generated by Django 4.1.2 on 2022-10-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '__first__'),
        ('reservation', '0009_alter_reservation_guest_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='length',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='massage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='massage.massage'),
        ),
    ]
