# Generated by Django 4.1.2 on 2022-11-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_massage_id'),
        ('reservation', '0010_remove_reservation_length_remove_reservation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='massage_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
