# Generated by Django 4.1.2 on 2022-11-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('massage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=200)),
                ('massage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='massage.massage')),
            ],
        ),
    ]
