# Generated by Django 4.1.2 on 2022-10-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masseur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masseur',
            old_name='phone_number',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='masseur',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='masseur',
            name='location',
        ),
        migrations.AddField(
            model_name='masseur',
            name='info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
