# Generated by Django 4.1.2 on 2022-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masseur', '0002_rename_phone_number_masseur_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masseur',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
