# Generated by Django 4.1.2 on 2022-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0002_alter_massages_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='massages',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
