# Generated by Django 4.1.2 on 2022-10-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0003_massages_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='massages',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
